swagger: '2.0'
info:
  description: 'OpenAPI Specification for the Apigee mock target service endpoint.'
  version: 1.0.0
  title: Mock Target API
host: mocktarget.apigee.net
schemes:
  - http
  - https
paths:
  /:
    get:
      summary: View personalized greeting 
      operationId: personalized greeting /
      description: View a personalized greeting for the specified or guest user.
      produces:
        - text/plain
      parameters:
        - name: user
          in: query
          description: Your user name.
          required: false
          type: string
      responses:
        '200':
          description: Success
  /help:
    get:
      summary: Get help
      operationId: Get help /help
      description: View help information about available resources in HTML format.
      produces:
        - text/html
      responses:
        '200':
          description: Success
  /iloveapis:
    get:
      summary: View API affirmation
      operationId: API affirmation /iloveapis
      description: View API affirmation in HTML format.
      produces:
        - text/html
      responses:
        '200':
          description: Success
  /ip:
    get:
      summary: View IP address
      operationId: IP address /ip
      description: View the IP address of the client in JSON format.
      produces:
        - application/json
      responses:
        '200':
          description: Success
  /xml:
    get:
      summary: View XML response
      operationId: XML response /xml
      description: View a sample response in XML format.
      produces:
        - application/xml
      responses:
        '200':
          description: Success
  /json:
    get:
      summary: View JSON response
      operationId: JSON response /json
      description: View a sample response in JSON format.
      produces:
        - application/json
      responses:
        '200':
          description: Success
  /echo:
    get:
      summary: View request headers and body
      operationId: echo request /echo
      description: View the request headers and body in JSON format.
      produces:
        - application/json
      responses:
        '200':
          description: Success
    post:
      summary: Send request and view request headers and body
      produces:
        - application/json
        - application/xml
        - application/x-www-form-urlencoded
      operationId: echo request /echo
      description: 'Send a request and view the resulting request headers and body in JSON format.<p>The request payload can be specified using one of the following formats: application/json, application/x-www-form-urlencoded, or application/xml.'
      parameters:
        - name: body
          in: body
          description: 'Request payload in application/json, application/x-www-form-urlencoded, or application/xml format.'
          required: true
          schema:
            $ref: '#/definitions/request-body'
      responses:
        '200':
          description: Success
  /statuscode/{code}:
    get:
      summary: View status code and message
      operationId: status code and message /statuscode/{code}
      description: View status code and message for the specified value.
      produces:
        - application/json
      parameters:
        - name: code
          in: path
          description: HTTP status code.
          required: true
          type: string
      responses:
        '200':
          description: Success

definitions:
  request-body:
    properties:
      replace-me:
        type: object
        description: 'Replace with request payload in application/json, application/x-www-form-urlencoded, or application/xml format.'
